config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users do
    get :books, on: :member
  end
  
  resources :sessions

  resources :books

  namespace :admin do
    root 'users#index'

    resources :users do
      collection do
        get :search
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ActiveRecord::Base

  validates :user_id, presence: { message: "用户不能为空" }
  validates :meal, presence: { message: "菜名不能为空" }
  validates :times, presence: { message: "具体时间" }
  validates :day, presence: { message: "上/下午" }
  validates :payer, presence: { message: "付款人" }

  belongs_to :user
  has_many :books_tags, class_name: "BooksTags"
  has_many :tags, through: :books_tags


  def tags_string= one_tags
    self.tags.destroy_all

    one_tags.split(',').each do |tag|
      one_tag = Tag.find_by(title: tag)
      one_tag = Tag.new(title: tag) unless one_tag

      self.tags << one_tag
    end
  end

end

app/models/books_tags.rb
class BlogsTags < ActiveRecord::Base

  self.table_name = 'books_tags'

  validates_uniqueness_of :book_id, scope: [:tag_id]

  belongs_to :book
  belongs_to :tag

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  validates :title, uniqueness: { message: "标签已存在" }

  has_many :books_tags, class_name: "BooksTags"
  has_many :books, through: :books_tags

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :username, presence: { message: "用户名不能为空" }
  validates :username, uniqueness: { message: "用户名已存在" }

  has_many :books
  has_many :public_books, -> { where(is_public: true) },
    class_name: "Book"

  has_one :latest_book,  -> { order("id desc") }, class_name: :Book

  before_save :update_username

  # attr_accessor :old_password
  attr_accessor :password
  attr_accessor :password_confirmation

  validate :validate_password, on: :create
  before_create :set_password

  def self.authenticate username, password
    user = find_by(username: username)
    if user and user.valid_password?(password)
      user
    else
      nil
    end
  end

  def valid_password? password
    self.crypted_password == Digest::SHA256.hexdigest(password + self.salt)
  end

  private
  def validate_password
    if self.password.blank?
      self.errors.add(:password, "密码不能为空")
      return false
    end

    unless self.password == self.password_confirmation
      self.errors.add(:password_confirmation, "密码不一致")
      return false
    end

    return true
  end

  def set_password
    self.salt = Time.now.to_i
    self.crypted_password = Digest::SHA256.hexdigest(self.password + self.salt)
  end

  def update_username
    self.username = self.username.downcase
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  layout 'admin'

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order("id desc")
  end

  def search
    @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order("id desc").where(["username like ?", "%#{params[:username]}%"])

    render action: :index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Concerns::UserSession
  
  private
  def auth_user
    unless logged_in?
      flash[:notice] = "请登录"
      redirect_to new_session_path
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_filter :auth_user, except: [:show]

  def index
    @books = Book.page(params[:page] || 1).per_page(params[:per_page] || 10).
      order("id desc").where(is_public: true).includes(:tags, :user)
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.new(book_attrs)
    if @book.save
      flash[:notice] = "订单成功"
      redirect_to books_path
    else
      flash[:notice] = "订单创建失败"
      render action: :new
    end
  end

  def edit
    @book = current_user.books.find params[:id]
    render action: :new
  end

  def update
    @book = current_user.books.find params[:id]
    @book.attributes = book_attrs
    if @book.save
      flash[:notice] = "订单更新成功"
      redirect_to books_path
    else
      flash[:notice] = "订单更新失败"
      render action: :new
    end
  end

  private
  def book_attrs
    params.require(:book).permit(:name, :meal,  :times , :day , :payer ,:is_public, :tags_string)
  end

end

app/controllers/concerns/user_session.rb
module Concerns

  module UserSession
    def self.included base
      base.class_eval do
        helper_method :logged_in?
        helper_method :current_user
      end
    end

    def signin_user user
      session[:user_id] = user.id
    end

    def logout_user
      session[:user_id] = nil
    end

    def logged_in?
      !!session[:user_id]
    end

    def current_user
      if logged_in?
        @current_user ||= User.find_by(id: session[:user_id])
      else
        nil    
      end
    end

  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create

    @user = User.authenticate(params[:username], params[:password])
    if @user
      signin_user @user
      
      render json: {
        status: 'ok',
        msg: {
          redirect_url: root_path
        }
      }
    else
      render json: {
        status: 'error',
        msg: "用户名或密码不正确"
      }
    end
  end

  def destroy
    logout_user
    
    flash[:notice] = "退出成功"
    @user = User.find_by(username: params[:username], password: params[:passwod])
    if @user
      session[:user_id] = @user_id
      flash[:notice] = "登陆成功"
      redirect_to root_path
    else
      flash[:notice] = "用户名或密码不正确"
      render action: :new
    end
  end
  
 
end

app/controllers/uers_controller.rb
class UsersController < ApplicationController

  before_filter :auth_user, only: [:index]

  def index
    @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order("id desc")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_attrs)
    if @user.save
      flash[:notice] = "注册成功，请登录"
      redirect_to new_session_path
    else
      render action: :new
    end
  end

  def books
    @books = current_user.books.page(params[:page] || 1).per_page(params[:per_page] || 7)
      .order("id desc")
  end

  private
  def user_attrs
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @user = if session[:user_id]
      User.find session[:user_id]
    else
      nil
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/users/_one_user.html.erb
<tr>
  <td><%= user.id %></td>
  <td><%= user.username %></td>
  <td></td>
</tr>

app/views/admin/users/index.html.erb
<h1>管理后台 - 用户列表</h1>

<div class="row">
  <div class="col-sm-12">

    <form action="<%= search_admin_users_path %>" method="get">
      用户名：<input type="text" name="username" value="<%= params[:username] %>" />
      <input type="submit" name="搜索">
    </form>

    <table class="table">
      <tr>
        <th>ID</th>
        <th>用户名</th>
        <th></th>
      </tr>
      
      <%= render partial: "one_user", collection: @users, as: :user %>
    </table>

    <%= will_paginate @users %>
  </div>
</div>

app/views/books/_books.html.erb
<table class="table">
  <tr>
    <th>ID</th>
    <th>用户</th>
    <th>饭菜种类</th>
    <th>时间</th>
    <th>上/下午</th>
    <th>付款人</th>
    <th></th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td><%= blog.id %></td>
      <td><%= blog.user.username %></td>
      <td><%= blog.meal %></td>
      <td><%= blog.times %></td>
      <td><%= blog.day %></td>
      <td><%= blog.payer %></td>
    </tr>
  <% end -%>
</table>

<%= will_paginate @books %>

app/views/books/index.html.erb
<h1>我的订单</h1>

<div>
  <%= link_to "创建订单", new_book_path, class: "btn btn-primary" %>
  <% if logged_in? %>
    <%= link_to "我的订单", books_user_path(current_user), class: "btn btn-default" %>
  <% end -%>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= render 'books' %>
  </div>
</div>

app/views/books/new.html.erb
<h1><%= @book.new_record? ? '创建' : '编辑' %>订单</h1>

<div class="row">
  <div class="col-sm-5">
    <%= form_for @book, url: (@book.new_record? ? books_path : book_path(@book)), method: (@book.new_record? ? :post : :put) do |f| %>
      <div class="form-group">
        <ul class="list-unstyled">
          <% @book.errors.messages.values.flatten.each do |error| %>
            <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
          <% end -%>
        </ul>
      </div>

      <div class="form-group">
        <%= f.text_field :name, class: "form-control", placeholder: "用户" %>
      </div>

      <div class="form-group">
        <%= f.text_field :meal, class: "form-control", placeholder: "饭菜种类" %>
      </div>

      <div class="form-group">
        <%= f.text_field :times, class: "form-control", placeholder: "时间" %>
      </div>

      <div class="form-group">
        <%= f.text_field :day, class: "form-control", placeholder: "上/下午" %>
      </div>

      <div class="form-group">
        <%= f.text_field :payer, class: "form-control", placeholder: "付款人" %>
      </div>

      <div class="form-group">
        <input type="text" name="book[tags_string]" value="<%= @book.tags.map(&:title).join(',') %>" /><small>标签以逗号分隔</small>
      </div>

      <div class="form-group">
        <% [[true, "显示"], [false, "不显示"]].each do |public| %>
          <input type="radio" name="book[is_public]" value="<%= public.first %>" <%= 'checked' if @book.is_public == public.first %> /> <%= public.last %>
        <% end -%>
      </div>      

      <%= f.submit "保存", class: "btn btn-primary" %> 
    <% end -%>
  </div>

  <div class="col-sm-7">
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Circles后台管理</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header name="top">
      <nav class="navbar navbar-default navbar-fixed-top nav-color" role="navigation" id="nav">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header nav-color">
            <button id="nav_collapse" type="button" class="navbar-toggle toggle-btn" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-controls="bs-navbar-collapse-1">
              <span class="fa fa-bars fa-lg"></span>
            </button>
            <a class="navbar-brand custom-logo-link" href="/">
              Circles后台管理
            </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse nav-submenu-color collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right custom">
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="<%= admin_users_path %>">用户管理</a>
              </li>

              <% if logged_in? %>
                <li><%= link_to "#{current_user.username}, 退出", session_path(session[:user_id]), method: 'delete' %></li>
              <% else %>
                <li><%= link_to "登录", new_session_path %></li>
              <% end -%>
            </ul>
          </div>
          <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-->
      </nav>
    </header>

    <div class="container body-offset">
      <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end -%>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dinners</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag 'welcome' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header name="top">
      <nav class="navbar navbar-default navbar-fixed-top nav-color" role="navigation" id="nav">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header nav-color">
            <button id="nav_collapse" type="button" class="navbar-toggle toggle-btn" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-controls="bs-navbar-collapse-1">
              <span class="fa fa-bars fa-lg"></span>
            </button>
            <a class="navbar-brand custom-logo-link" href="/">
              Dinners
            </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse nav-submenu-color collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right custom">
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="<%= users_path %>">用户</a>
              </li>

              <% if logged_in? %>
                <li><%= link_to "#{current_user.username}, 退出", session_path(session[:user_id]), method: 'delete' %></li>
              <% else %>
                <li><%= link_to "登录", new_session_path %></li>
              <% end -%>
              
              <li><%= link_to "订单", books_path %></li>

            </ul>
          </div>
          <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-->
      </nav>
    </header>

    <div class="container body-offset">
      <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end -%>
      
      <%= yield %>
    </div>

  <%= javascript_include_tag 'application' %>
  <%= yield :javascripts %>
  </body>
</html>

app/views/users/books.html.erb
<h1><%= current_user.username %>的订单</h1>

<div>
  <%= link_to "创建订单", new_book_path, class: "btn btn-primary" %> 
  <%= link_to "我的订单", books_user_path(current_user), class: "btn btn-default" %>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= render 'books/books' %>
  </div>
</div>

app/views/users/new.html.erb
<h1>用户注册</h1>

<div class="row">
  <div class="col-sm-5">
    <%= form_for @user, url: users_path, method: :post do |f| %>
      <div class="form-group">
        <ul class="list-unstyled">
          <% @user.errors.messages.values.flatten.each do |error| %>
            <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
          <% end -%>
        </ul>
      </div>

      <div class="form-group">
        <%= f.text_field :username, class: "form-control", placeholder: "用户名" %>
      </div>

      <div class="form-group">
        <%= f.password_field :password, class: "form-control", placeholder: "密码" %>
      </div>

      <div class="form-group">
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "密码确认" %>
      </div>

      <%= f.submit "注册", class: "btn btn-primary" %> 
      <%= link_to "登录", new_session_path %>
    <% end -%>
  </div>

  <div class="col-sm-7">
  </div>
</div>

app/views/welcome/index.html.erb
<% if @user %>
  <h1>欢迎你!, <%= @user.username %></h1>
<% else %>
  <h1>Dinners 首页</h1>
<% end -%>

<%= content_for :javascripts do %>
  <script type="text/javascript">
    var pageTitle = "首页";
  </script>
<% end -%>